### ISSUE TITLE
terminal_info fail

### ISSUE THREAD

**Issue by taleslimaf** [lucas-campagna/mt5linux#4]
Fala @lucas-campagna , blz? Estava testando aqui e estou tendo problemas com o comando "terminal_info".

`
TypeError: descriptor '__len__' of 'tuple' object needs an argument

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "...site-packages\rpyc\core\protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "...site-packages\rpyc\core\protocol.py", line 635, in _handle_callattr
    return self._handle_call(obj, args, kwargs)
  File "...site-packages\rpyc\core\protocol.py", line 609, in _handle_call
    return obj(*args, **dict(kwargs))
TypeError: descriptor '__len__' of 'tuple' object needs an argument
`

Você teve algum problema similar?

**Comment by lucas-campagna** [comment]
Opa, @taleslimaf .

Cara, não tenho certeza do que seja, teria que olhar o código. Mas adianto que há algumas estruturas/classes que não são passadas do python do windows para o python do linux. Isso acontece porque o python no linux não sabe como estruturar (ou montar) o dado recebido, porque não existe uma classe que represente o dado. Isso seria algo para trabalharmos no futuro.

Mas tem há uma solução. A própria biblioteca Metatrader5 te possibilita representar tais estrutuas no formato dicionário (dict). Bastaria chamar o método (salvo engano) `_asdict()`.
