### ISSUE TITLE
MetaTrader5 + Python + Linux

### ISSUE THREAD

**Issue by PedroIAgithub** [lucas-campagna/mt5linux#9]
Olá, gostaria de saber como baixar a biblioteca MetaTrader5 no python pelo sistema operacional linux.

Estou usando :

- Ubuntu 22.04.1 LTS

- Python 3.5.2

- Anaconda 4.2.0 (64-bit)

Aparentemente a biblioteca MetaTrader5 só funciona no Windows. A forma de usá-la seria instalando o Wine. E instalar o python para Windows usando o Wine, depois baixar a biblioteca MetaTrader5 no python do Windows. E no python do linux baixar a biblioteca mt5linux, conforme o tutorial :

- htt ps: //pypi. org/project/mt5linux/

Queria saber se é necessário tudo isso, se não tem uma forma mais efetiva de fazer.

Ainda sim quando procuro pelo mt5linux no terminal do ubuntu (também tentei instalar), usando o comando :

---------------------------------------

conda search mt5linux

---------------------------------------

Aparece isso:

-----------------------------------------------------------------------------------------------------------------------

PackagesNotFoundError: The following packages are not available from current channels:

  - mt5linux

Current channels:

  - htt ps: //repo. anaconda. com  /pkgs/main/linux-64
  - htt ps: //repo. anaconda. com /pkgs/main/noarch
  - htt ps: //repo. anaconda. com /pkgs/free/linux-64
  - htt ps: //repo. anaconda. com /pkgs/free/noarch
  - htt ps: //repo. anaconda. com /pkgs/r/linux-64
  - htt ps: //repo. anaconda. com /pkgs/r/noarch
  - htt ps: //repo. anaconda. com /pkgs/pro/linux-64
  - htt ps: //repo. anaconda. com /pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    htt ps:// anaconda. org

and use the search bar at the top of the page.

-----------------------------------------------------------------------------------------------------------------------

É necessário instalar outro canal ? É necessário usar outra versão do python ?

Pacotes, bibliotecas e módulos são a mesma coisa ? Porque uma biblioteca só funciona no Windows ?

Estou começando por agora nisso.

Desde já agradeço.

**Comment by lucas-campagna** [comment]
Olá, @PedroIAgithub, perdoa-me a demora para respondê-lo.

Não é possível instalar MetaTrader5 no linux. Este repositório vem justamente para resolver este problema e permitir usá-la no Linux.

Você está correto, este é o caminho para a instalação e uso desta lib. Baixe o Wine e siga as instruções de instalação no [README.md](https://github.com/lucas-campagna/mt5linux/blob/master/README.md) do projeto. Eu atualizei as instruções de instalação graças a esta [issue](https://github.com/lucas-campagna/mt5linux/issues/10).
